config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    devise_scope :user do
      post 'guest_sign_in' => 'sessions#guest_sign_in'
    end
    resources:posts do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources:users, only:[:show, :edit, :update] do
      get 'my_page' => 'users#my_page'
    end
    get 'suspended' => 'users#suspended'
  end

  namespace :admin do
    root to: 'posts#index'
    get 'search' => 'searches#search'
    resources:posts, only:[:index, :show, :destroy] do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
    end
    resources:users, only:[:index, :show, :update] do
      patch 'suspended' => 'users#suspended'
    end
    resources:comments, only:[:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word], true)
      @users2 = User.looks(params[:search], params[:word], false)
    else
      @places = Post.looks(params[:search], params[:word])
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word], true)
      @users2 = User.looks(params[:search], params[:word], false)
    else
      @places = Post.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/searches/search.html.erb
<h2 class="m-3">検索結果</h2>

<div class="row">
  <table class="table">
    <% if @range == "User" %>
      <% @users.each do |user| %>
        <tr>
          <th>投稿者</th>
          <td><%= user.nickname %></td>
          <td><%= link_to "投稿一覧", user_path(user.id) %></td>
        </tr>
      <% end %>
      <% @users2.each do |user| %>
        <tr>
          <th>投稿者</th>
          <td><%= user.fullname %></td>
          <td><%= link_to "投稿一覧", user_path(user.id) %></td>
        </tr>
      <% end %>
    <% else %>
      <% @places.each do |place| %>
        <tr>
          <th>タイトル</th>
          <td><%= link_to place.title, post_path(place.id) %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>