config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    devise_scope :user do
      post 'guest_sign_in' => 'sessions#guest_sign_in'
    end
    resources:posts do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources:users, only:[:show, :edit, :update] do
      get 'my_page' => 'users#my_page'
    end
    get 'suspended' => 'users#suspended'
  end

  namespace :admin do
    root to: 'posts#index'
    get 'search' => 'searches#search'
    resources:posts, only:[:index, :show, :destroy] do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
    end
    resources:users, only:[:index, :show, :update] do
      patch 'suspended' => 'users#suspended'
    end
    resources:comments, only:[:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tag_managers, dependent: :destroy
  has_many :tags, through: :tag_managers
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  # addressカラムを基準に緯度経度を算出する。
  geocoded_by :address
  # 住所変更時に緯度経度も変更する。
  before_validation :geocode

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @place = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @place = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @place = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @place = Post.where("title LIKE?","%#{word}%")
    else
      @place = Post.all
    end
  end

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @places = Post.all
  end

  def show
    @place = Post.find(params[:id])
    @user = @place.user
    @comment = Comment.new
    @post_tags = @place.tags
  end

  def destroy
    place = Post.find(params[:id])
    place.destroy
    redirect_to admin_posts_path
  end

  def search_tag
    #検索結果画面でもタグ一覧表示
    @tag_list = Tag.all
    #検索されたタグを受け取る
    @tag = Tag.find(params[:id])
    #検索されたタグに紐づく投稿を表示
    @places = @tag.posts
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="row">
  <h2 class="m-3">スポット一覧</h2>

  <div class="col-sm-12">
    <div class="card-group">
    <% @places.each do |place| %>
      <div class="col-sm-3">
        <div class="card mb-2">
          <%= image_tag place.get_image, class:"card-img-top thumbnail-img" %>
          <div class="card-body">
            <h5 class="card-title text-truncate"><%= place.title %></h5>
            <p class="card-text text-right"><%= place.created_at.strftime('%Y/%m/%d') %></p>
            <%= link_to admin_post_path(place.id), class:"btn btn-outline-primary" do %>
              <i class="fas fa-crosshairs"></i> Pick up!
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/search_tag.html.erb
<div class="row justify-content-center">
  <div class="col-sm-10">
    <h2 class="m-3">
      <i class="fas fa-tag"></i> <%= @tag.name %>  の投稿一覧
    </h2>

    <div class="card-deck">
    <% @places.each do |place| %>
      <div class="col-sm-4">
        <div class="card mb-2">
          <%= image_tag place.get_image, class:"card-img-top", width:"100%", height:"180px" %>
          <div class="card-body">
            <p class="card-text">
              <%= link_to admin_post_path(place.id) do %>
                <%= place.title.truncate(25) %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>

  <div class="col-sm-2 text-truncate">
    <h3 class="m-3">
      <i class="fas fa-tags"></i>タグ一覧
    </h3>
    <table class="table m-3">
      <% @tag_list.each do |list|%>
      <tr>
        <td>
          <%= link_to list.name, admin_post_search_tag_path(@places, list) %>
          <%= "(#{list.posts.count})" %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/posts/show.html.erb
<h2 class="m-3">スポット詳細</h2>

<div class="row justify-content-center">
  <div class="col-sm-5">
    <%= image_tag @place.get_image, class:"text-center m-3 show-img" %>
  </div>

  <div class="col-sm-5">
    <h3><%= @place.title %></h3>
    <p><%= safe_join(@place.body.split("\n"),tag(:br)) %></p>
    <div class="text-right">
      <%= link_to "削除", admin_post_path(@place.id), method: :delete, "data-confirm" => "この投稿を削除します。よろしいですか？", class:"btn btn-outline-danger" %>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-sm-5">
    <div id='map'></div>

    <style>
      #map{
        height: 500px;
        width: 400px;
      }
    </style>

    <script>
      let map;
      function initMap(){
        geocoder = new google.maps.Geocoder()

        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>},
          zoom: 12
        });

        marker = new google.maps.Marker({
          position: {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>},
          map: map
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>
  </div>

  <div class="col-sm-5">
    <h4>スポット情報</h4>
    <table class="table table-borderless">
      <tr>
        <th><i class="fas fa-map-marker-alt"></i> 住所</th>
        <td><%= @place.address %></td>
      </tr>
      <tr>
        <th><i class="fas fa-clock"></i> 営業時間</th>
        <td><%= safe_join(@place.business_hour.split("\n"),tag(:br)) %></td>
      </tr>
      <tr>
        <th><i class="fas fa-coins"></i> 料金</th>
        <td><%= safe_join(@place.price.split("\n"),tag(:br)) %></td>
      </tr>
      <tr>
        <th class="text-truncate"><i class="fas fa-walking"></i> アクセス方法</th>
        <td><%= safe_join(@place.access.split("\n"),tag(:br)) %></td>
      </tr>
      <tr>
        <th><i class="fas fa-user-edit"></i> 投稿者</th>
        <td>
          <% if @user.nickname.present? %>
            <%= @user.nickname %>
          <% else %>
            <%= @user.last_name %> <%= @user.first_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th><i class="fas fa-tag"></i> タグ</th>
        <td>
          <% @post_tags.each do |tag| %>
            <%= link_to tag.name, admin_post_search_tag_path(@place, tag) %>
            <%= "(#{tag.posts.count})" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-sm-10 offset-sm-1">
    <p class="text-right">コメント件数：<%= @place.comments.count %></p>
    <table class="table">
      <tr class="table-secondary">
        <th>コメント</th>
        <th>投稿者</th>
        <th>投稿日</th>
        <th></th>
      </tr>
      <% @place.comments.each do |comment| %>
      <tr>
        <td>
          <%= comment.comment %>
        </td>
        <td>
          <% if comment.user.nickname.present? %>
            <%= comment.user.nickname %>
          <% else %>
            <%= comment.user.last_name %>
            <%= comment.user.first_name %>
          <% end %>
        </td>
        <td>
          <%= comment.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
          <%= link_to "削除", admin_comment_path(comment.post, comment), method: :delete, class:"btn btn-outline-warning" %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>

</div>