config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    devise_scope :user do
      post 'guest_sign_in' => 'sessions#guest_sign_in'
    end
    resources:posts do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources:users, only:[:show, :edit, :update] do
      get 'my_page' => 'users#my_page'
    end
    get 'suspended' => 'users#suspended'
  end

  namespace :admin do
    root to: 'posts#index'
    get 'search' => 'searches#search'
    resources:posts, only:[:index, :show, :destroy] do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
    end
    resources:users, only:[:index, :show, :update] do
      patch 'suspended' => 'users#suspended'
    end
    resources:comments, only:[:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def fullname
    last_name + first_name
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "ゲスト"
      user.first_name = "ユーザー"
      user.phone_number = "01234567890"
    end
  end

  def self.looks(search, word, nickname)
    if nickname
      # ニックネームが登録されているものを検索
      if search == "perfect_match"
        @user = User.where.not(nickname:nil).where("nickname LIKE?", "#{word}")
      elsif search == "forward_match"
        @user = User.where.not(nickname:nil).where("nickname LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where.not(nickname:nil).where("nickname LIKE?","%#{word}")
      elsif search == "partial_match"
        @user = User.where.not(nickname:nil).where("nickname LIKE?","%#{word}%")
      else
        @user = User.where.not(nickname:nil)
      end
    else
      # ニックネームが登録されていないものを検索
      if search == "perfect_match"
        @user = User.where(nickname:nil).where("first_name LIKE? OR last_name LIKE?", "#{word}", "#{word}")
      elsif search == "forward_match"
        @user = User.where(nickname:nil).where("first_name LIKE? OR last_name LIKE?","#{word}%","#{word}%")
      elsif search == "backward_match"
        @user = User.where(nickname:nil).where("first_name LIKE? OR last_name LIKE?","%#{word}","%#{word}")
      elsif search == "partial_match"
        @user = User.where(nickname:nil).where("first_name LIKE? OR last_name LIKE?","%#{word}%","%#{word}%")
      else
        @user = User.where(nickname:nil)
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id)
  end

  def suspended
    user = User.find(params[:user_id])
    user.update(suspended: true)
    reset_session
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :nickname, :phone_number)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<h2 class="m-3">会員一覧</h2>

<div class="row">
  <div class="col-sm-10 offset-sm-1">
    <table class="table">
      <thead>
          <tr class="bg-light">
            <th scope="col">会員ID</th>
            <th scope="col">氏名</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to user.fullname, admin_user_path(user) %></td>
              <td><%= user.email %></td>
              <td>
                <% if user.suspended? == true %>
    	            <p class="text-danger">停止</p>
				        <% else %>
				          <p class="text-success">有効</p>
				        <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<h2 class="m-3"><%= @user.fullname %>さんの登録情報詳細</h2>

<div class="row">
  <div class="col-sm-10 offset-sm-1">
    <table class="table table-borderless">
      <tr>
        <th>会員ID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @user.last_name %>&ensp;<%= @user.first_name %></td>
      </tr>
      <tr>
        <th>ニックネーム</th>
        <td><%= @user.nickname %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @user.phone_number %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @user.suspended? == true %>
    	       <p class="text-danger">停止</p>
			    <% else %>
			      <p class="text-success">有効</p>
			    <% end %>
        </td>
      </tr>
    </table>

    <div class="text-center">
      <%= link_to "アカウントを停止する", admin_user_suspended_path(@user), method: :patch, "data-confirm" => "本当に停止しますか?", class:"btn btn-outline-danger" %>
    </div>
  </div>
</div>