config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    devise_scope :user do
      post 'guest_sign_in' => 'sessions#guest_sign_in'
    end
    resources:posts do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources:users, only:[:show, :edit, :update] do
      get 'my_page' => 'users#my_page'
    end
    get 'suspended' => 'users#suspended'
  end

  namespace :admin do
    root to: 'posts#index'
    get 'search' => 'searches#search'
    resources:posts, only:[:index, :show, :destroy] do
      get 'search_tag/:id' => 'posts#search_tag', as: :search_tag
    end
    resources:users, only:[:index, :show, :update] do
      patch 'suspended' => 'users#suspended'
    end
    resources:comments, only:[:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pick up! & Go!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

　　<%= stylesheet_link_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light">
        <%= link_to root_path, class:"navbar-brand" do %>
          <h3><i class="fas fa-crosshairs"></i> Pick up! & Go! <i class="fas fa-running"></i></h3>
        <% end %>
        <ul class="nav justify-content-end">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", user_my_page_path(current_user.id), class:"nav-link btn btn-outline-info mr-1" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class:"nav-link btn btn-outline-info mr-1" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規投稿", new_post_path, class:"nav-link btn btn-outline-info mr-1" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link btn btn-outline-danger" %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_posts_path, class:"nav-link btn btn-outline-info mr-1" %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_users_path, class:"nav-link btn btn-outline-info mr-1" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link btn btn-outline-danger" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class:"nav-link btn btn-outline-info mr-1" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class:"nav-link btn btn-outline-info mr-1" %>
            </li>
            <li class="nav-item">
              <%= link_to "管理者ログイン", new_admin_session_path, class:"nav-link btn btn-outline-secondary" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>

      <div class="container">
        <%= yield %>
      </div>

    <footer class="text-center">
      <nav class="navbar justify-content-center">
        <h4 class="mt-5">
          ようこそ！Pick up! & Go!へ！
        </h4>
      </nav>
    </footer>
  </body>
</html>